import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import { checkAuth } from "../lib/auth"; // ✅ Server-side import
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionUserId = await checkAuth(); // ✅ Now works since RootLayout is a Server Component

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-base-200 text-base-content`}
      >
        <div className="min-h-screen flex flex-col">
          {/* Navbar */}
          <nav className="navbar bg-base-100 shadow-sm fixed top-0 left-0 right-0 z-50">
            <div className="flex-1">
              <Link href="/" className="btn btn-ghost text-xl">
                BANGER SUPER COOL GAME AAHAAHAHAAHA
              </Link>
            </div>
            <div className="flex-none">
              <ul className="menu menu-horizontal px-1">
                {sessionUserId == null ? (
                  <>
                    <li>
                      <Link href="/auth/login">Login</Link>
                    </li>
                    <li>
                      <Link href="/auth/reg">Register</Link>
                    </li>
                  </>
                ) : (
                  <>
                    <li>
                      <Link href="/game">Game</Link>
                    </li>
                    <li>
                      <Link href="/champions">Champions</Link>
                    </li>
                    <li>
                      <Link href="/auth/logout">Logout</Link>
                    </li>
                    <li>
                      <Link href="/leaderboard">Leaderboard</Link>
                    </li>
                  </>
                )}
              </ul>
            </div>
          </nav>

          {/* Main Content */}
          <main className="flex-grow pt-20 px-4 sm:px-6 lg:px-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
